services:
  fit_data_db:
    build:
      context: ./fit_data_db
      secrets:
        - source: ya_disk_oauth_token
          mode: 0400
      image: fit_data_db
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: fit_data_db
    ports:
      - "8000:5432"

  fit_data_db_backuper:
    build:
      context: ./fit_data_db_backuper
      secrets:
        - source: ya_disk_oauth_token
          mode: 0400
      image: fit_data_db_backuper
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: fit_data_db
    ports:
      - "8001:5432"
    depends_on:
      - fit_data_db

  fit_data_bot:
    build:
      context: ./fit_data_bot
      secrets:
        - source: ya_disk_oauth_token
          mode: 0400
        - source: tg_bot_token
          mode: 0400
      image: fit_data_bot
    depends_on:
      - fit_data_db

secrets:
  ya_disk_oauth_token:
    file: ./secrets/ya_disk_oauth_token
  tg_bot_token:
    file: ./secrers/bot_token
    